name: Workflow Sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
jobs:
  sync:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: File Sync
        uses: EdgeApp/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            EdgeApp/edge-conventions
            EdgeApp/edge-sync-server
            EdgeApp/edge-login-server
            EdgeApp/edge-info-server
            EdgeApp/edge-referral-server
            EdgeApp/edge-rates-server
            EdgeApp/edge-logs-server
            EdgeApp/edge-react-gui
          FILES: |
            .github/workflows/pr-checks.yml=.github/workflows/pr-checks.yml
            .github/workflows/pr-rebase.yml=.github/workflows/pr-rebase.yml
          TOKEN: ${{ secrets.WORKFLOW_SYNC_TOKEN }}